num = [4,2,5,3,6,1,2,1,2,8,9,7]
num.sort()
print(num)
num.reverse()
print(num)
num.append(10)
print(num)
num.insert(0, 0)
print(num)
num.remove(2)
print(num)  
num.pop()
print(num)  
num.clear() 
print(num)
num.extend([11, 12, 13])
print(num)
num2 = num.copy()
print(num2)
num2.sort()
print(num2)